# Build stage
FROM rust:1.89-slim-bookworm AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release


# Runtime stage
FROM debian:bookworm-slim AS runtime
COPY --from=builder /app/target/release/sample-rust /usr/local/bin/sample-rust
EXPOSE 80
CMD ["sample-rust"]
